---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "SLS-XXX"
    versioning-strategy: "lockfile-only"
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "SLS-XXX"
    versioning-strategy: lockfile-only
    groups:
      rust-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: all
