---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "SLS-<insert ticket # here>"
    versioning-strategy: "lockfile-only"
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
